### ISSUE TITLE
plan price shoud be the public price of the article

### ISSUE THREAD

**Issue by MatSarr** [elabore-coop/elabore-odoo-addons#1]
Budget --> add section or sub section or article

plan price shoud be the public price of the article and not stay to 0 if a public price is defined in the article

![image](https://user-images.githubusercontent.com/46820746/139659306-a2690458-bc4f-4cf1-a826-f9da3e0657cb.png)

**Comment by stephansainleger** [comment]
OK for articles.
For sections and sub-sections, the current process is to show the average amount of the child lines (original process). I can modify the process so that :
-  if the average is zéro, then the public price is displayed. 
- OR it does not the average of the child prices, but the sum of the child prices, and if the sum is zero, then I display the public price
What do you prefer? Or do you have another idea?

**Comment by MatSarr** [comment]
I think I prefer "OR it does not the average of the child prices, but the sum of the child prices, and if the sum is zero, then I display the public price" what do you think?

**Comment by stephansainleger** [comment]
I agree, i think it makes more sense.

**Comment by stephansainleger** [comment]
Question : for an article, is the user supposed to be able to modify the plan price directly in the budget_forecast? Or do we consider that, if he wants to modify it, he has to modify the public price of the product?

**Comment by MatSarr** [comment]
I reckon It should be the same way as the creation of sale order and invoice: 
In budget, You add a line with a product and the product cost (not the public price) is added in the budget in plan price
Then you can modify the plan price in the budget without modify the product cost of the product
If the product cost empty, the budget plan price is also empty

**Comment by stephansainleger** [comment]
New algorithm delivered with commit https://github.com/elabore-coop/elabore-odoo-addons/commit/730cd26b634c72e0010c3ae8fdd83eaea32a1565 .
I let you test it and tell me if that is ok.
